// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: driverstream.proto

package DriverStream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LatLng struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatLng) Reset() {
	*x = LatLng{}
	mi := &file_driverstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatLng) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatLng) ProtoMessage() {}

func (x *LatLng) ProtoReflect() protoreflect.Message {
	mi := &file_driverstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatLng.ProtoReflect.Descriptor instead.
func (*LatLng) Descriptor() ([]byte, []int) {
	return file_driverstream_proto_rawDescGZIP(), []int{0}
}

func (x *LatLng) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *LatLng) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_driverstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driverstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_driverstream_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateStatusRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *UpdateStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Location      *LatLng                `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Speed         float64                `protobuf:"fixed64,3,opt,name=speed,proto3" json:"speed,omitempty"`
	Heading       float64                `protobuf:"fixed64,4,opt,name=heading,proto3" json:"heading,omitempty"`
	Ts            int64                  `protobuf:"varint,5,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationRequest) Reset() {
	*x = UpdateLocationRequest{}
	mi := &file_driverstream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationRequest) ProtoMessage() {}

func (x *UpdateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driverstream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateLocationRequest) Descriptor() ([]byte, []int) {
	return file_driverstream_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateLocationRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *UpdateLocationRequest) GetLocation() *LatLng {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *UpdateLocationRequest) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *UpdateLocationRequest) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *UpdateLocationRequest) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type DriverAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverAck) Reset() {
	*x = DriverAck{}
	mi := &file_driverstream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverAck) ProtoMessage() {}

func (x *DriverAck) ProtoReflect() protoreflect.Message {
	mi := &file_driverstream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverAck.ProtoReflect.Descriptor instead.
func (*DriverAck) Descriptor() ([]byte, []int) {
	return file_driverstream_proto_rawDescGZIP(), []int{3}
}

func (x *DriverAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetNearbyDriversRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *LatLng                `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Radius        int32                  `protobuf:"varint,2,opt,name=radius,proto3" json:"radius,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNearbyDriversRequest) Reset() {
	*x = GetNearbyDriversRequest{}
	mi := &file_driverstream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNearbyDriversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearbyDriversRequest) ProtoMessage() {}

func (x *GetNearbyDriversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driverstream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearbyDriversRequest.ProtoReflect.Descriptor instead.
func (*GetNearbyDriversRequest) Descriptor() ([]byte, []int) {
	return file_driverstream_proto_rawDescGZIP(), []int{4}
}

func (x *GetNearbyDriversRequest) GetLocation() *LatLng {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *GetNearbyDriversRequest) GetRadius() int32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *GetNearbyDriversRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type NearbyDriver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Distance      float64                `protobuf:"fixed64,2,opt,name=distance,proto3" json:"distance,omitempty"`
	Lat           float64                `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,4,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyDriver) Reset() {
	*x = NearbyDriver{}
	mi := &file_driverstream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyDriver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyDriver) ProtoMessage() {}

func (x *NearbyDriver) ProtoReflect() protoreflect.Message {
	mi := &file_driverstream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyDriver.ProtoReflect.Descriptor instead.
func (*NearbyDriver) Descriptor() ([]byte, []int) {
	return file_driverstream_proto_rawDescGZIP(), []int{5}
}

func (x *NearbyDriver) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *NearbyDriver) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *NearbyDriver) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *NearbyDriver) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type GetNearbyDriversResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drivers       []*NearbyDriver        `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNearbyDriversResponse) Reset() {
	*x = GetNearbyDriversResponse{}
	mi := &file_driverstream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNearbyDriversResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearbyDriversResponse) ProtoMessage() {}

func (x *GetNearbyDriversResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driverstream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearbyDriversResponse.ProtoReflect.Descriptor instead.
func (*GetNearbyDriversResponse) Descriptor() ([]byte, []int) {
	return file_driverstream_proto_rawDescGZIP(), []int{6}
}

func (x *GetNearbyDriversResponse) GetDrivers() []*NearbyDriver {
	if x != nil {
		return x.Drivers
	}
	return nil
}

type PrepareAssignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	CandidateIds  []string               `protobuf:"bytes,2,rep,name=candidate_ids,json=candidateIds,proto3" json:"candidate_ids,omitempty"`
	TtlSeconds    int32                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareAssignRequest) Reset() {
	*x = PrepareAssignRequest{}
	mi := &file_driverstream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareAssignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareAssignRequest) ProtoMessage() {}

func (x *PrepareAssignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driverstream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareAssignRequest.ProtoReflect.Descriptor instead.
func (*PrepareAssignRequest) Descriptor() ([]byte, []int) {
	return file_driverstream_proto_rawDescGZIP(), []int{7}
}

func (x *PrepareAssignRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *PrepareAssignRequest) GetCandidateIds() []string {
	if x != nil {
		return x.CandidateIds
	}
	return nil
}

func (x *PrepareAssignRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type PrepareAssignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queued        bool                   `protobuf:"varint,1,opt,name=queued,proto3" json:"queued,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareAssignResponse) Reset() {
	*x = PrepareAssignResponse{}
	mi := &file_driverstream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareAssignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareAssignResponse) ProtoMessage() {}

func (x *PrepareAssignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driverstream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareAssignResponse.ProtoReflect.Descriptor instead.
func (*PrepareAssignResponse) Descriptor() ([]byte, []int) {
	return file_driverstream_proto_rawDescGZIP(), []int{8}
}

func (x *PrepareAssignResponse) GetQueued() bool {
	if x != nil {
		return x.Queued
	}
	return false
}

func (x *PrepareAssignResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type ClaimTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimTripRequest) Reset() {
	*x = ClaimTripRequest{}
	mi := &file_driverstream_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTripRequest) ProtoMessage() {}

func (x *ClaimTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driverstream_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTripRequest.ProtoReflect.Descriptor instead.
func (*ClaimTripRequest) Descriptor() ([]byte, []int) {
	return file_driverstream_proto_rawDescGZIP(), []int{9}
}

func (x *ClaimTripRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *ClaimTripRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type ClaimTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimTripResponse) Reset() {
	*x = ClaimTripResponse{}
	mi := &file_driverstream_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTripResponse) ProtoMessage() {}

func (x *ClaimTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driverstream_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTripResponse.ProtoReflect.Descriptor instead.
func (*ClaimTripResponse) Descriptor() ([]byte, []int) {
	return file_driverstream_proto_rawDescGZIP(), []int{10}
}

func (x *ClaimTripResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_driverstream_proto protoreflect.FileDescriptor

const file_driverstream_proto_rawDesc = "" +
	"\n" +
	"\x12driverstream.proto\x12\x06driver\",\n" +
	"\x06LatLng\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\"J\n" +
	"\x13UpdateStatusRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xa0\x01\n" +
	"\x15UpdateLocationRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12*\n" +
	"\blocation\x18\x02 \x01(\v2\x0e.driver.LatLngR\blocation\x12\x14\n" +
	"\x05speed\x18\x03 \x01(\x01R\x05speed\x12\x18\n" +
	"\aheading\x18\x04 \x01(\x01R\aheading\x12\x0e\n" +
	"\x02ts\x18\x05 \x01(\x03R\x02ts\"%\n" +
	"\tDriverAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"s\n" +
	"\x17GetNearbyDriversRequest\x12*\n" +
	"\blocation\x18\x01 \x01(\v2\x0e.driver.LatLngR\blocation\x12\x16\n" +
	"\x06radius\x18\x02 \x01(\x05R\x06radius\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"k\n" +
	"\fNearbyDriver\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x01R\bdistance\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x04 \x01(\x01R\x03lng\"J\n" +
	"\x18GetNearbyDriversResponse\x12.\n" +
	"\adrivers\x18\x01 \x03(\v2\x14.driver.NearbyDriverR\adrivers\"u\n" +
	"\x14PrepareAssignRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12#\n" +
	"\rcandidate_ids\x18\x02 \x03(\tR\fcandidateIds\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x05R\n" +
	"ttlSeconds\"E\n" +
	"\x15PrepareAssignResponse\x12\x16\n" +
	"\x06queued\x18\x01 \x01(\bR\x06queued\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\"H\n" +
	"\x10ClaimTripRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\"+\n" +
	"\x11ClaimTripResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xfa\x02\n" +
	"\rDriverService\x12>\n" +
	"\fUpdateStatus\x12\x1b.driver.UpdateStatusRequest\x1a\x11.driver.DriverAck\x12B\n" +
	"\x0eUpdateLocation\x12\x1d.driver.UpdateLocationRequest\x1a\x11.driver.DriverAck\x12U\n" +
	"\x10GetNearbyDrivers\x12\x1f.driver.GetNearbyDriversRequest\x1a .driver.GetNearbyDriversResponse\x12L\n" +
	"\rPrepareAssign\x12\x1c.driver.PrepareAssignRequest\x1a\x1d.driver.PrepareAssignResponse\x12@\n" +
	"\tClaimTrip\x12\x18.driver.ClaimTripRequest\x1a\x19.driver.ClaimTripResponseBFZDgithub.com/UITGo/driver-stream/internal/pb/DriverStream;DriverStreamb\x06proto3"

var (
	file_driverstream_proto_rawDescOnce sync.Once
	file_driverstream_proto_rawDescData []byte
)

func file_driverstream_proto_rawDescGZIP() []byte {
	file_driverstream_proto_rawDescOnce.Do(func() {
		file_driverstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_driverstream_proto_rawDesc), len(file_driverstream_proto_rawDesc)))
	})
	return file_driverstream_proto_rawDescData
}

var file_driverstream_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_driverstream_proto_goTypes = []any{
	(*LatLng)(nil),                   // 0: driver.LatLng
	(*UpdateStatusRequest)(nil),      // 1: driver.UpdateStatusRequest
	(*UpdateLocationRequest)(nil),    // 2: driver.UpdateLocationRequest
	(*DriverAck)(nil),                // 3: driver.DriverAck
	(*GetNearbyDriversRequest)(nil),  // 4: driver.GetNearbyDriversRequest
	(*NearbyDriver)(nil),             // 5: driver.NearbyDriver
	(*GetNearbyDriversResponse)(nil), // 6: driver.GetNearbyDriversResponse
	(*PrepareAssignRequest)(nil),     // 7: driver.PrepareAssignRequest
	(*PrepareAssignResponse)(nil),    // 8: driver.PrepareAssignResponse
	(*ClaimTripRequest)(nil),         // 9: driver.ClaimTripRequest
	(*ClaimTripResponse)(nil),        // 10: driver.ClaimTripResponse
}
var file_driverstream_proto_depIdxs = []int32{
	0,  // 0: driver.UpdateLocationRequest.location:type_name -> driver.LatLng
	0,  // 1: driver.GetNearbyDriversRequest.location:type_name -> driver.LatLng
	5,  // 2: driver.GetNearbyDriversResponse.drivers:type_name -> driver.NearbyDriver
	1,  // 3: driver.DriverService.UpdateStatus:input_type -> driver.UpdateStatusRequest
	2,  // 4: driver.DriverService.UpdateLocation:input_type -> driver.UpdateLocationRequest
	4,  // 5: driver.DriverService.GetNearbyDrivers:input_type -> driver.GetNearbyDriversRequest
	7,  // 6: driver.DriverService.PrepareAssign:input_type -> driver.PrepareAssignRequest
	9,  // 7: driver.DriverService.ClaimTrip:input_type -> driver.ClaimTripRequest
	3,  // 8: driver.DriverService.UpdateStatus:output_type -> driver.DriverAck
	3,  // 9: driver.DriverService.UpdateLocation:output_type -> driver.DriverAck
	6,  // 10: driver.DriverService.GetNearbyDrivers:output_type -> driver.GetNearbyDriversResponse
	8,  // 11: driver.DriverService.PrepareAssign:output_type -> driver.PrepareAssignResponse
	10, // 12: driver.DriverService.ClaimTrip:output_type -> driver.ClaimTripResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_driverstream_proto_init() }
func file_driverstream_proto_init() {
	if File_driverstream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_driverstream_proto_rawDesc), len(file_driverstream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_driverstream_proto_goTypes,
		DependencyIndexes: file_driverstream_proto_depIdxs,
		MessageInfos:      file_driverstream_proto_msgTypes,
	}.Build()
	File_driverstream_proto = out.File
	file_driverstream_proto_goTypes = nil
	file_driverstream_proto_depIdxs = nil
}
