// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: driverstream.proto

package DriverStream

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DriverService_UpdateStatus_FullMethodName     = "/driver.DriverService/UpdateStatus"
	DriverService_UpdateLocation_FullMethodName   = "/driver.DriverService/UpdateLocation"
	DriverService_GetNearbyDrivers_FullMethodName = "/driver.DriverService/GetNearbyDrivers"
	DriverService_PrepareAssign_FullMethodName    = "/driver.DriverService/PrepareAssign"
	DriverService_ClaimTrip_FullMethodName        = "/driver.DriverService/ClaimTrip"
)

// DriverServiceClient is the client API for DriverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriverServiceClient interface {
	UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*DriverAck, error)
	UpdateLocation(ctx context.Context, in *UpdateLocationRequest, opts ...grpc.CallOption) (*DriverAck, error)
	GetNearbyDrivers(ctx context.Context, in *GetNearbyDriversRequest, opts ...grpc.CallOption) (*GetNearbyDriversResponse, error)
	PrepareAssign(ctx context.Context, in *PrepareAssignRequest, opts ...grpc.CallOption) (*PrepareAssignResponse, error)
	ClaimTrip(ctx context.Context, in *ClaimTripRequest, opts ...grpc.CallOption) (*ClaimTripResponse, error)
}

type driverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverServiceClient(cc grpc.ClientConnInterface) DriverServiceClient {
	return &driverServiceClient{cc}
}

func (c *driverServiceClient) UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*DriverAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverAck)
	err := c.cc.Invoke(ctx, DriverService_UpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) UpdateLocation(ctx context.Context, in *UpdateLocationRequest, opts ...grpc.CallOption) (*DriverAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverAck)
	err := c.cc.Invoke(ctx, DriverService_UpdateLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GetNearbyDrivers(ctx context.Context, in *GetNearbyDriversRequest, opts ...grpc.CallOption) (*GetNearbyDriversResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNearbyDriversResponse)
	err := c.cc.Invoke(ctx, DriverService_GetNearbyDrivers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) PrepareAssign(ctx context.Context, in *PrepareAssignRequest, opts ...grpc.CallOption) (*PrepareAssignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareAssignResponse)
	err := c.cc.Invoke(ctx, DriverService_PrepareAssign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) ClaimTrip(ctx context.Context, in *ClaimTripRequest, opts ...grpc.CallOption) (*ClaimTripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimTripResponse)
	err := c.cc.Invoke(ctx, DriverService_ClaimTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverServiceServer is the server API for DriverService service.
// All implementations must embed UnimplementedDriverServiceServer
// for forward compatibility.
type DriverServiceServer interface {
	UpdateStatus(context.Context, *UpdateStatusRequest) (*DriverAck, error)
	UpdateLocation(context.Context, *UpdateLocationRequest) (*DriverAck, error)
	GetNearbyDrivers(context.Context, *GetNearbyDriversRequest) (*GetNearbyDriversResponse, error)
	PrepareAssign(context.Context, *PrepareAssignRequest) (*PrepareAssignResponse, error)
	ClaimTrip(context.Context, *ClaimTripRequest) (*ClaimTripResponse, error)
	mustEmbedUnimplementedDriverServiceServer()
}

// UnimplementedDriverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDriverServiceServer struct{}

func (UnimplementedDriverServiceServer) UpdateStatus(context.Context, *UpdateStatusRequest) (*DriverAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedDriverServiceServer) UpdateLocation(context.Context, *UpdateLocationRequest) (*DriverAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLocation not implemented")
}
func (UnimplementedDriverServiceServer) GetNearbyDrivers(context.Context, *GetNearbyDriversRequest) (*GetNearbyDriversResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNearbyDrivers not implemented")
}
func (UnimplementedDriverServiceServer) PrepareAssign(context.Context, *PrepareAssignRequest) (*PrepareAssignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareAssign not implemented")
}
func (UnimplementedDriverServiceServer) ClaimTrip(context.Context, *ClaimTripRequest) (*ClaimTripResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimTrip not implemented")
}
func (UnimplementedDriverServiceServer) mustEmbedUnimplementedDriverServiceServer() {}
func (UnimplementedDriverServiceServer) testEmbeddedByValue()                       {}

// UnsafeDriverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriverServiceServer will
// result in compilation errors.
type UnsafeDriverServiceServer interface {
	mustEmbedUnimplementedDriverServiceServer()
}

func RegisterDriverServiceServer(s grpc.ServiceRegistrar, srv DriverServiceServer) {
	// If the following call pancis, it indicates UnimplementedDriverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DriverService_ServiceDesc, srv)
}

func _DriverService_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_UpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).UpdateStatus(ctx, req.(*UpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_UpdateLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).UpdateLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_UpdateLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).UpdateLocation(ctx, req.(*UpdateLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GetNearbyDrivers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNearbyDriversRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GetNearbyDrivers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GetNearbyDrivers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GetNearbyDrivers(ctx, req.(*GetNearbyDriversRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_PrepareAssign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareAssignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).PrepareAssign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_PrepareAssign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).PrepareAssign(ctx, req.(*PrepareAssignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_ClaimTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ClaimTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ClaimTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ClaimTrip(ctx, req.(*ClaimTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DriverService_ServiceDesc is the grpc.ServiceDesc for DriverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DriverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "driver.DriverService",
	HandlerType: (*DriverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateStatus",
			Handler:    _DriverService_UpdateStatus_Handler,
		},
		{
			MethodName: "UpdateLocation",
			Handler:    _DriverService_UpdateLocation_Handler,
		},
		{
			MethodName: "GetNearbyDrivers",
			Handler:    _DriverService_GetNearbyDrivers_Handler,
		},
		{
			MethodName: "PrepareAssign",
			Handler:    _DriverService_PrepareAssign_Handler,
		},
		{
			MethodName: "ClaimTrip",
			Handler:    _DriverService_ClaimTrip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driverstream.proto",
}
